---
- name: Copy the ps1 powershell script
  win_copy:
    src: files/bluetools.ps1
    dest: C:\terraform\bluetools.ps1

- name: Execute the blue team security tools ps1 script
  win_shell: powershell.exe C:\terraform\bluetools.ps1
  args:
    executable: cmd
  register: results

#- name:
#  replace:
#    path: ${path.module}/files/config2.yaml
#    regexp: "  pinned_server_name: VelociraptorServer"
#    replace: "  use_self_signed_ssl: true\n  pinned_server_name: VelociraptorServer"

- debug:
    var: results.stdout_lines 
